### ISSUE TITLE
Removing releases from pypi.org breaks older versions of pytest-homeassistant-custom-component

### ISSUE THREAD

**Issue by pnbruckner** [cdce8p/mypy-dev#20]
https://github.com/MatthewFlamm/pytest-homeassistant-custom-component is used for testing home assistant custom integrations. In my case, I use a few different releases of pytest-homeassistant-custom-component to test my custom integrations with older home assistant releases. (I try to maintain backwards compatibility for a while for my users. E.g., I'm typically maintaining support now for 2023.8.0 and newer.)

This all worked very well until just recently, when releases of mypy-dev were deleted from pypi.org.

Please keep this in mind before deleting releases from pypi.org.

See https://github.com/MatthewFlamm/pytest-homeassistant-custom-component/issues/195 for some background detail.

**Comment by cdce8p** [comment]
Thanks for the issue. I'm aware that deleting old releases from PyPI isn't ideal. Unfortunately, I don't have unlimited storage. It just fills up quickly when doing 5 or more alpha releases and one or two beta ones per mypy release. Each one with 20 compiled wheels.

My (unofficial) policy so far has been to keep all alpha releases for the current one and the last beta release for each one after that.

That works well for Home Assistant as test requirements are only pinned in the dev environment.

If you do need to pin it, I'd suggest to use >=1.11.0a3,<1.11.0 or even better: Just pin the last mypy version instead.

Hope that explains it, even if it might not have been the answer you're looking for. I'm open to suggestions how to deal with the upload limit (without requesting a limit increase).

**Comment by pnbruckner** [comment]
So I don't work on pytest-homeassistant-custom_component, I just use it.

It's fine for Home Assistant itself, since it only cares about the latest & greatest. But for custom integrations, it's good to support at least some older versions of HA, and it's even better if it can be tested on older versions.

Anyway, I think it was determined that mypy-dev should not have been a requirement for the use of pytest-homeassistant-custom-component, but only for its development, which I believe was just fixed, so going forward this shouldn't be a problem anymore. It just sucks that it killed any version of pytest-homeassistant-custom-component older than 2 days.
